package com.hrms.dept.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import org.hibernate.envers.Audited;


// Example of Lombok if you added the Lombok dependency

//import lombok.NoArgsConstructor;
@Audited
@Entity
@Table(name = "departments")
public class Department {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long departmentId;

    @Column(nullable = false, length = 100)
    private String departmentName;

    @Column(length = 50)
    private String departmentCode;

    private Long parentDepartmentId; // We'll handle the foreign key logic later

    private Long departmentHeadId; // Will link with Employees eventually

    @Column(length = 500)
    private String description;

    @Column(length = 100)
    private String location;

    private Double budgetAllocation;

    @Column(length = 100)
    private String departmentEmail;

    @Column(length = 50)
    private String departmentPhoneNumber;

    private String createdBy;
    private LocalDateTime createdDate;

    private String lastUpdatedBy;
    private LocalDateTime lastUpdatedDate;

    // Constructors
    public Department() { }

    public Department(String departmentName, String departmentCode, Long parentDepartmentId, Long departmentHeadId,
                      String description, String location, Double budgetAllocation, String departmentEmail,
                      String departmentPhoneNumber, String createdBy, LocalDateTime createdDate, String lastUpdatedBy,
                      LocalDateTime lastUpdatedDate) {
        this.departmentName = departmentName;
        this.departmentCode = departmentCode;
        this.parentDepartmentId = parentDepartmentId;
        this.departmentHeadId = departmentHeadId;
        this.description = description;
        this.location = location;
        this.budgetAllocation = budgetAllocation;
        this.departmentEmail = departmentEmail;
        this.departmentPhoneNumber = departmentPhoneNumber;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.lastUpdatedBy = lastUpdatedBy;
        this.lastUpdatedDate = lastUpdatedDate;
    }

    // Getters and setters (can be generated by Lombok if available)
    public Long getDepartmentId() {
        return departmentId;
    }
    public void setDepartmentId(Long departmentId) {
        this.departmentId = departmentId;
    }

    public String getDepartmentName() {
        return departmentName;
    }
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    public String getDepartmentCode() {
        return departmentCode;
    }
    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode;
    }

    public Long getParentDepartmentId() {
        return parentDepartmentId;
    }
    public void setParentDepartmentId(Long parentDepartmentId) {
        this.parentDepartmentId = parentDepartmentId;
    }

    public Long getDepartmentHeadId() {
        return departmentHeadId;
    }
    public void setDepartmentHeadId(Long departmentHeadId) {
        this.departmentHeadId = departmentHeadId;
    }

    public String getDescription() {
        return description;
    }
    public void setDescription(String description) {
        this.description = description;
    }

    public String getLocation() {
        return location;
    }
    public void setLocation(String location) {
        this.location = location;
    }

    public Double getBudgetAllocation() {
        return budgetAllocation;
    }
    public void setBudgetAllocation(Double budgetAllocation) {
        this.budgetAllocation = budgetAllocation;
    }

    public String getDepartmentEmail() {
        return departmentEmail;
    }
    public void setDepartmentEmail(String departmentEmail) {
        this.departmentEmail = departmentEmail;
    }

    public String getDepartmentPhoneNumber() {
        return departmentPhoneNumber;
    }
    public void setDepartmentPhoneNumber(String departmentPhoneNumber) {
        this.departmentPhoneNumber = departmentPhoneNumber;
    }

    public String getCreatedBy() {
        return createdBy;
    }
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public LocalDateTime getCreatedDate() {
        return createdDate;
    }
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    public LocalDateTime getLastUpdatedDate() {
        return lastUpdatedDate;
    }
    public void setLastUpdatedDate(LocalDateTime lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }
}
