-- ============================================================
-- V10__create_employees_aud.sql
-- Audit table for com.hrms.employee.entity.Employee
-- ============================================================

CREATE TABLE IF NOT EXISTS employees_aud (
    employee_id      BIGINT   NOT NULL,
    rev              INTEGER  NOT NULL,
    revtype          SMALLINT NOT NULL,
    -- Columns from employees:
    background_check_date      DATE,
    background_check_status    VARCHAR(32),
    blood_group                VARCHAR(4),
    city                       VARCHAR(100),
    contract_end_date          DATE,
    contract_type              VARCHAR(32),
    country                    VARCHAR(100),
    created_by                 VARCHAR(100),
    created_date               TIMESTAMP,
    data_consent               BOOLEAN,
    data_consent_date          DATE,
    date_of_birth              DATE,
    department_id              BIGINT,
    designation                VARCHAR(100),
    emergency_address          VARCHAR(255),
    emergency_contact_name     VARCHAR(100),
    emergency_email            VARCHAR(100),
    emergency_phone            VARCHAR(30),
    emergency_relationship     VARCHAR(30),
    employee_type              VARCHAR(30),
    employment_status          VARCHAR(30),
    first_name                 VARCHAR(100),
    gender                     VARCHAR(30),
    grade_level                VARCHAR(30),
    hire_date                  DATE,
    job_title                  VARCHAR(100),
    last_name                  VARCHAR(100),
    last_updated_by            VARCHAR(100),
    last_updated_date          TIMESTAMP,
    manager_id                 BIGINT,
    marital_status             VARCHAR(30),
    middle_name                VARCHAR(100),
    nationality                VARCHAR(50),
    personal_email             VARCHAR(100),
    personal_phone_number      VARCHAR(30),
    photo                      BYTEA,
    postal_code                VARCHAR(20),
    probation_end_date         DATE,
    probation_start_date       DATE,
    shift_details              VARCHAR(100),
    ssn                        VARCHAR(30),
    state_province             VARCHAR(100),
    street_address             VARCHAR(255),
    tax_identification_number  VARCHAR(50),
    termination_date           DATE,
    visa_expiry_date           DATE,
    visa_issue_date            DATE,
    visa_number                VARCHAR(50),
    visa_type                  VARCHAR(30),
    work_email                 VARCHAR(100),
    work_location              VARCHAR(100),
    work_phone_number          VARCHAR(30),
    -- PK & FK
    PRIMARY KEY (rev, employee_id),
    FOREIGN KEY (rev) REFERENCES revinfo(rev) ON DELETE CASCADE
);
