-- Drop tables if they already exist (this is safe during development; in production, careful use is advised)
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS departments CASCADE;

-- Create Department table
CREATE TABLE departments (
  department_id SERIAL PRIMARY KEY,
  department_name VARCHAR(100) NOT NULL,
  department_code VARCHAR(50),
  parent_department_id BIGINT,
  department_head_id BIGINT,
  description VARCHAR(500),
  location VARCHAR(100),
  budget_allocation NUMERIC,
  department_email VARCHAR(100),
  department_phone_number VARCHAR(50),
  created_by VARCHAR(255),
  created_date TIMESTAMP,
  last_updated_by VARCHAR(255),
  last_updated_date TIMESTAMP
);

-- Create Employee table
CREATE TABLE employees (
  employee_id SERIAL PRIMARY KEY,
  first_name VARCHAR(255),
  middle_name VARCHAR(255),
  last_name VARCHAR(255),
  date_of_birth DATE,
  gender VARCHAR(50),
  marital_status VARCHAR(50),
  nationality VARCHAR(100),
  ssn VARCHAR(100),
  personal_email VARCHAR(255),
  personal_phone_number VARCHAR(50),
  street_address VARCHAR(255),
  city VARCHAR(100),
  state_province VARCHAR(100),
  postal_code VARCHAR(50),
  country VARCHAR(100),
  blood_group VARCHAR(50),
  photo VARCHAR(255),
  job_title VARCHAR(255),
  employee_type VARCHAR(100),
  employment_status VARCHAR(50),
  hire_date DATE,
  termination_date DATE,
  department_id BIGINT REFERENCES departments(department_id),
  manager_id BIGINT REFERENCES employees(employee_id),
  work_location VARCHAR(255),
  work_email VARCHAR(255),
  work_phone_number VARCHAR(50),
  grade_level VARCHAR(50),
  shift_details VARCHAR(255),
  probation_start_date DATE,
  probation_end_date DATE,
  contract_type VARCHAR(100),
  contract_end_date DATE,
  emergency_contact_name VARCHAR(255),
  emergency_relationship VARCHAR(100),
  emergency_phone VARCHAR(50),
  emergency_email VARCHAR(255),
  emergency_address VARCHAR(255),
  visa_type VARCHAR(100),
  visa_number VARCHAR(100),
  visa_issue_date DATE,
  visa_expiry_date DATE,
  tax_identification_number VARCHAR(100),
  background_check_status VARCHAR(100),
  background_check_date DATE,
  data_consent BOOLEAN,
  data_consent_date DATE,
  created_by VARCHAR(255),
  created_date TIMESTAMP,
  last_updated_by VARCHAR(255),
  last_updated_date TIMESTAMP
);
